-- Business Question:
-- Which customer states generate the highest revenue for Olist?

-- Approach:
-- Step 1: Compute total revenue at the order level (to avoid double counting item rows)
-- Step 2: Join orders with customers to attach geographic (state) information
-- Step 3: Aggregate revenue and activity metrics at the state level
-- Step 4: Rank states by total revenue using a window function

WITH order_revenue AS (
    -- Step 1:
    -- Each order can have multiple items, so we first calculate total revenue per order
    SELECT
        oi.order_id,
        SUM(oi.price + oi.freight_value) AS order_revenue
    FROM order_items oi
    GROUP BY oi.order_id
),
delivered_orders_with_state AS (
    -- Step 2:
    -- Join orders with customers to get customer location (state)
    -- Also attach the computed order-level revenue
    -- Filter only delivered orders to reflect completed transactions
    SELECT
        o.order_id,
        c.customer_id,
        c.customer_unique_id,
        c.customer_state,
        orv.order_revenue
    FROM orders o
    JOIN customers c
        ON o.customer_id = c.customer_id
    JOIN order_revenue orv
        ON o.order_id = orv.order_id
    WHERE o.order_status = 'delivered'
),
state_summary AS (
    -- Step 3:
    -- Aggregate metrics at the state level
    -- total_orders: number of orders per state
    -- total_customers: number of unique customers per state
    -- total_revenue: total revenue generated by the state
    -- avg_order_revenue: average order value in the state
    SELECT
        customer_state,
        COUNT(DISTINCT order_id) AS total_orders,
        COUNT(DISTINCT customer_unique_id) AS total_customers,
        SUM(order_revenue) AS total_revenue,
        AVG(order_revenue) AS avg_order_revenue
    FROM delivered_orders_with_state
    GROUP BY customer_state
),

